/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export enum PetCountry {
  "People's_Republic_of_China" = "People's Republic of China",
  Uruguay = "Uruguay",
}
